- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  name: Start Loki
  tasks:
    - name: Start Loki container
      docker_container:
        image: "grafana/loki:3.0.1"
        name: "ansible-loki-callback-test"
        auto_remove: true
        published_ports:
          - "3100:3100"
        state: started
      register: loki_container
    - name: Wait for Loki to be ready
      uri:
        url: "http://localhost:3100/ready"
      register: _result
      until: _result.status == 200
      retries: 100
      delay: 5

- import_playbook: "default/playbook.yaml"

- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  name: "Checking results"
  tasks:
    - name: "Fetching number of recorded logs"
      uri:
        url: http://localhost:3100/loki/api/v1/query_range?query={{ '{run="test"}' | urlencode }}
        body_format: json
      register: logs
    - name: tmp1
      ansible.builtin.debug:
        var: expected_records
    - name: tmp2
      ansible.builtin.debug:
        var: logs.json.data.result | length
    - fail:
        msg: "Invalid number of records"
      when: logs.json.data.result | length != expected_records | int

- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  name: Stop Loki
  tasks:
    - name: Stop Loki container
      docker_container:
        name: "ansible-loki-callback-test"
        state: stopped
